routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/dashboard', 'Admin\DashboardController@index')
    ->name('dashboard')
    ->middleware(['auth']);

Route::resource('admin', 'Admin\AdminController')
    ->middleware('auth');

Route::resource('banner', 'Admin\BannerController')
    ->middleware('auth');

Route::resource('about', 'Admin\AboutController')
    ->middleware('auth')
    ->only(['edit', 'update']);

Route::resource('program', 'Admin\ProgramController')
    ->middleware('auth');

Route::resource('teacher', 'Admin\TeacherController')
    ->middleware('auth');

Route::resource('event', 'Admin\EventController')
    ->middleware('auth');

Route::resource('news', 'Admin\NewsController')
    ->middleware('auth');

Route::resource('gallery', 'Admin\GalleryController')
    ->middleware('auth');

Route::get('gallery-stage/{stage}', 'Admin\GalleryController@indexStage')
    ->name('gallery.stage')
    ->middleware('auth');

Route::prefix('pdb')
    ->name('pdb.')
    ->middleware(['auth'])
    ->group(function () {

        Route::get('manage/list/{status}/{stage}', 'Admin\RegisterController@index')
            ->name('index');

        Route::get('manage/detail/{id}', 'Admin\RegisterController@detail')
            ->name('detail');

        Route::get('manage/print/{id}', 'Admin\RegisterController@print')
            ->name('print');

        Route::put('manage/process/{id}', 'Admin\RegisterController@process')
            ->name('process');
    });




Route::get('/', 'Frontend\HomeController@index')
    ->name('front.home');

Route::get('profil-kami', 'Frontend\AboutController@index')
    ->name('front.about');

Route::get('program-unggulan', 'Frontend\ProgramController@index')
    ->name('front.program');

Route::get('program-unggulan/{slug}', 'Frontend\ProgramController@detail')
    ->name('front.program.detail');

Route::get('acara', 'Frontend\EventController@index')
    ->name('front.event');

Route::get('acara/{slug}', 'Frontend\EventController@detail')
    ->name('front.event.detail');

Route::get('berita', 'Frontend\NewsController@index')
    ->name('front.news');

Route::get('berita/{slug}', 'Frontend\NewsController@detail')
    ->name('front.news.detail');

Route::get('galeri', 'Frontend\GalleryController@index')
    ->name('front.gallery');

Route::get('galeri/{stage}', 'Frontend\GalleryController@indexStage')
    ->name('front.gallery.stage');

Route::get('kontak', 'Frontend\ContactController@index')
    ->name('front.contact');

Route::prefix('pdb')
    ->name('front.pdb.')
    ->group(function () {

        Route::get('step-1', 'Frontend\RegisterController@stepOne')
            ->name('step-1');

        Route::get('step-2', 'Frontend\RegisterController@stepTwo')
            ->name('step-2');

        Route::get('step-3', 'Frontend\RegisterController@stepThree')
            ->name('step-3');

        Route::get('step-4', 'Frontend\RegisterController@stepFour')
            ->name('step-4');

        Route::get('step-5', 'Frontend\RegisterController@stepFive')
            ->name('step-5');

        Route::get('step-6', 'Frontend\RegisterController@stepSix')
            ->name('step-6');

        Route::get('complete', 'Frontend\RegisterController@complete')
            ->name('complete');

        Route::post('store/{step}', 'Frontend\RegisterController@store')
            ->name('store');
    });

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    //
}

app/Http/Controllers/Admin/EventController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Event;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreEvent;
use App\Http\Requests\UpdateEvent;
use App\Services\CloudinaryService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.event.index', [
            'events' => Event::orderBy('id', 'DESC')->paginate(8)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.event.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEvent $request)
    {
        $request->validated();

        $event = new Event;
        $event->title = $request->input('title');
        $event->description = $request->input('description');
        $event->image = CloudinaryService::upload($request->file('image'));
        $event->date = $request->input('date');
        $event->time = $request->input('time');
        $event->slug = Str::slug($event->title);

        if($event->save()) {
            return redirect()->route('event.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.event.edit', [
            'event' => Event::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEvent $request, $id)
    {
        $request->validated();

        $event = Event::findOrFail($id);
        $event->title = $request->input('title');
        $event->description = $request->input('description');
        $event->date = $request->input('date');
        $event->time = $request->input('time');
        $event->slug = Str::slug($event->title);

        if ($request->file('image')) {
            CloudinaryService::remove($event->image);
            $event->image = CloudinaryService::upload($request->file('image'));
        }

        if($event->save()) {
            return redirect()->route('event.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $event = Event::findOrFail($id);
        if($event->delete()) {
            CloudinaryService::remove($event->image);
            return redirect()->route('event.index');
        }
    }
}

app/Http/Controllers/Frontend/EventController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Event;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class EventController extends Controller
{
    public function index()
    {
        return view('frontend.event.index', [
            'events' => Event::orderBy('id', 'DESC')->limit(3)->get(),
            'acara' => Event::orderBy('id', 'DESC')->paginate(9),
        ]);
    }

    public function detail($slug = null)
    {
        return view('frontend.event.detail', [
            'events' => Event::orderBy('id', 'DESC')->limit(3)->get(),
            'event' => Event::where('slug', $slug)->firstOrFail() 
        ]);
    }
}

resources/views/admin/event/create.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Event</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('event.index') }}">Event</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Create
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height justify-content-center">
                <div class="col-xl-10 col-lg-10 col-md-10 col-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-body">
                                <form method="POST" action="{{ route('event.store') }}" enctype="multipart/form-data" class="forms-sample">
                                    @csrf
                                    <div class="form-group">
                                        <label>Title</label>
                                        <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" placeholder="Title" value="{{ old('title') }}" required>
                                        @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Topic</label>
                                        <textarea name="description" class="form-control @error('description') is-invalid @enderror" placeholder="Description">{{ old('description') }}</textarea>
                                        @error('description')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Image <i style="font-size: 10px">(maks 850 x 850 350kb)</i></label>
                                        <input type="file" name="image" class="form-control @error('image') is-invalid @enderror" required>
                                        @error('image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Date</label>
                                        <input type="date" name="date" class="form-control @error('date') is-invalid @enderror" placeholder="Date Held" value="{{ old('date') }}" required>
                                        @error('date')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Time</label>
                                        <input type="time" name="time" class="form-control @error('time') is-invalid @enderror" placeholder="Time Held" value="{{ old('time') }}" required>
                                        @error('time')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-rounded mr-2">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/event/edit.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Event</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('event.index') }}">Event</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Edit
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height justify-content-center">
                <div class="col-xl-10 col-lg-10 col-md-10 col-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-body">
                                <form method="POST" action="{{ route('event.update', $event->id) }}" enctype="multipart/form-data" class="forms-sample">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group">
                                        <label>Title</label>
                                        <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" placeholder="Title" value="{{ $event->title }}" required>
                                        @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Topic</label>
                                        <textarea name="description" class="form-control @error('description') is-invalid @enderror" placeholder="Description">{{ $event->description }}</textarea>
                                        @error('description')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Image <i style="font-size: 10px">(maks 850 x 850 350kb)</i></label>
                                        <br>
                                        <img src="{{ $event->image }}" class="img-fluid mb-1" alt="">
                                        <input type="file" name="image" class="form-control @error('image') is-invalid @enderror">
                                        @error('image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Date</label>
                                        <input type="date" name="date" class="form-control @error('date') is-invalid @enderror" placeholder="Date Held" value="{{ $event->date }}" required>
                                        @error('date')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Time</label>
                                        <input type="time" name="time" class="form-control @error('time') is-invalid @enderror" placeholder="Time Held" value="{{ $event->time }}" required>
                                        @error('time')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-rounded mr-2">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/event/index.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Event</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('event.index') }}">Event</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Index
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height">
                @foreach ($events as $event)
                <div class="col-lg-3 col-md-3">
                    <div class="card">
                        <img class="block-event__card-image" src="{{ $event->image }}" alt="Card image">
                        <div class="card-body">
                            <h4 class="card-title block-event__card-body-title">{{ $event->title }}</h4>
                            <h6 class="card-subtitle text-muted">
                                <i class="ft-calendar"></i> {{ $event->date }} - {{ date('H:i A', strtotime($event->time)) }}
                            </h6>
                        </div>
                        <div class="card-footer block-event__card-footer border-top-blue-grey border-top-lighten-5 text-muted">
                            <div class="block-event__card-footer-grid">
                                <div class="block-event__card-footer-grid-item">
                                    <button class="btn btn-info full-width" title="Edit" onclick="window.location='{{ route('event.edit', $event->id) }}'">
                                        <i class="ft-edit"></i> Edit
                                    </button>
                                </div>
                                <div class="block-event__card-footer-grid-item">
                                    <form action="{{ route('event.destroy', $event->id) }}" method="POST" onsubmit="return confirm('Are you sure?')">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger full-width" title="Delete">
                                            <i class="ft-trash"></i> Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            <div class="row block-nav justify-content-center">
                <div class="col-lg-12 col-7 block-nav__box">
                   {{ $events->links() }}
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-primary btn-sticky no-padding" title="Add New" onclick="window.location='{{ route('event.create') }}'">
        <i class="ft-plus la-3x"></i>
    </button>
</div>
@endsection