routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/dashboard', 'Admin\DashboardController@index')
    ->name('dashboard')
    ->middleware(['auth']);

Route::resource('admin', 'Admin\AdminController')
    ->middleware('auth');

Route::resource('banner', 'Admin\BannerController')
    ->middleware('auth');

Route::resource('about', 'Admin\AboutController')
    ->middleware('auth')
    ->only(['edit', 'update']);

Route::resource('program', 'Admin\ProgramController')
    ->middleware('auth');

Route::resource('teacher', 'Admin\TeacherController')
    ->middleware('auth');

Route::resource('event', 'Admin\EventController')
    ->middleware('auth');

Route::resource('news', 'Admin\NewsController')
    ->middleware('auth');

Route::resource('gallery', 'Admin\GalleryController')
    ->middleware('auth');

Route::get('gallery-stage/{stage}', 'Admin\GalleryController@indexStage')
    ->name('gallery.stage')
    ->middleware('auth');

Route::prefix('pdb')
    ->name('pdb.')
    ->middleware(['auth'])
    ->group(function () {

        Route::get('manage/list/{status}/{stage}', 'Admin\RegisterController@index')
            ->name('index');

        Route::get('manage/detail/{id}', 'Admin\RegisterController@detail')
            ->name('detail');

        Route::get('manage/print/{id}', 'Admin\RegisterController@print')
            ->name('print');

        Route::put('manage/process/{id}', 'Admin\RegisterController@process')
            ->name('process');
    });




Route::get('/', 'Frontend\HomeController@index')
    ->name('front.home');

Route::get('profil-kami', 'Frontend\AboutController@index')
    ->name('front.about');

Route::get('program-unggulan', 'Frontend\ProgramController@index')
    ->name('front.program');

Route::get('program-unggulan/{slug}', 'Frontend\ProgramController@detail')
    ->name('front.program.detail');

Route::get('acara', 'Frontend\EventController@index')
    ->name('front.event');

Route::get('acara/{slug}', 'Frontend\EventController@detail')
    ->name('front.event.detail');

Route::get('berita', 'Frontend\NewsController@index')
    ->name('front.news');

Route::get('berita/{slug}', 'Frontend\NewsController@detail')
    ->name('front.news.detail');

Route::get('galeri', 'Frontend\GalleryController@index')
    ->name('front.gallery');

Route::get('galeri/{stage}', 'Frontend\GalleryController@indexStage')
    ->name('front.gallery.stage');

Route::get('kontak', 'Frontend\ContactController@index')
    ->name('front.contact');

Route::prefix('pdb')
    ->name('front.pdb.')
    ->group(function () {

        Route::get('step-1', 'Frontend\RegisterController@stepOne')
            ->name('step-1');

        Route::get('step-2', 'Frontend\RegisterController@stepTwo')
            ->name('step-2');

        Route::get('step-3', 'Frontend\RegisterController@stepThree')
            ->name('step-3');

        Route::get('step-4', 'Frontend\RegisterController@stepFour')
            ->name('step-4');

        Route::get('step-5', 'Frontend\RegisterController@stepFive')
            ->name('step-5');

        Route::get('step-6', 'Frontend\RegisterController@stepSix')
            ->name('step-6');

        Route::get('complete', 'Frontend\RegisterController@complete')
            ->name('complete');

        Route::post('store/{step}', 'Frontend\RegisterController@store')
            ->name('store');
    });

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    //
}

app/Http/Controllers/Admin/TeacherController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreTeacher;
use App\Http\Requests\UpdateTeacher;
use App\Services\CloudinaryService;
use App\Teacher;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.teacher.index', [
            'teachers' => Teacher::orderBy('id', 'DESC')->paginate(8)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.teacher.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTeacher $request)
    {
        $request->validated();

        $teacher = new Teacher;
        $teacher->name = $request->input('name');
        $teacher->motto = $request->input('motto');
        $teacher->position = $request->input('position');
        $teacher->avatar = CloudinaryService::upload($request->file('avatar'));
        $teacher->media = json_encode([
            'facebook' => $request->input('facebook'),
            'twitter' => $request->input('twitter'),
            'linkedin' => $request->input('linkedin'),
            'instagram' => $request->input('instagram'),
        ]);
        $teacher->slug = Str::slug($teacher->name);

        if($teacher->save()) {
            return redirect()->route('teacher.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function show(Teacher $teacher)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.teacher.edit', [
            'teacher' => Teacher::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTeacher $request, $id)
    {
        $request->validated();

        $teacher = Teacher::findOrFail($id);
        $teacher->name = $request->input('name');
        $teacher->motto = $request->input('motto');
        $teacher->position = $request->input('position');
        $teacher->media = json_encode([
            'facebook' => $request->input('facebook'),
            'twitter' => $request->input('twitter'),
            'linkedin' => $request->input('linkedin'),
            'instagram' => $request->input('instagram'),
        ]);
        $teacher->slug = Str::slug($teacher->name);

        if ($request->file('avatar')) {
            CloudinaryService::remove($teacher->avatar);
            $teacher->avatar = CloudinaryService::upload($request->file('avatar'));
        }

        if($teacher->save()) {
            return redirect()->route('teacher.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $teacher = Teacher::findOrFail($id);
        if($teacher->delete()) {
            CloudinaryService::remove($teacher->avatar);
            return redirect()->route('teacher.index');
        }
    }
}

resources/views/admin/teacher/create.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Teacher</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('teacher.index') }}">Teacher</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Create
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height justify-content-center">
                <div class="col-xl-10 col-lg-10 col-md-10 col-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-body">
                                <form method="POST" action="{{ route('teacher.store') }}" enctype="multipart/form-data" class="forms-sample">
                                    @csrf
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Name" value="{{ old('name') }}" required>
                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Position</label>
                                        <input type="text" name="position" class="form-control @error('position') is-invalid @enderror" placeholder="Position" value="{{ old('position') }}" required>
                                        @error('position')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Motto</label>
                                        <input type="text" name="motto" class="form-control @error('motto') is-invalid @enderror" placeholder="Motto" value="{{ old('motto') }}" required>
                                        @error('motto')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Avatar <i style="font-size: 10px">(maks 600 x 700 250kb)</i></label>
                                        <input type="file" name="avatar" class="form-control @error('avatar') is-invalid @enderror" required>
                                        @error('avatar')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Facebook Link</label>
                                                <input type="text" name="facebook" class="form-control @error('facebook') is-invalid @enderror" placeholder="Facebook" value="{{ old('facebook') }}">
                                                @error('facebook')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Twitter Link</label>
                                                <input type="text" name="twitter" class="form-control @error('twitter') is-invalid @enderror" placeholder="Twitter" value="{{ old('twitter') }}">
                                                @error('twitter')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>LinkedIn Link</label>
                                                <input type="text" name="linkedin" class="form-control @error('linkedin') is-invalid @enderror" placeholder="LinkedIn" value="{{ old('linkedin') }}">
                                                @error('linkedin')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Instagram Link</label>
                                                <input type="text" name="instagram" class="form-control @error('instagram') is-invalid @enderror" placeholder="Instagram" value="{{ old('instagram') }}">
                                                @error('instagram')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-rounded mr-2">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/teacher/edit.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Teacher</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('teacher.index') }}">Teacher</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Edit
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height justify-content-center">
                <div class="col-xl-10 col-lg-10 col-md-10 col-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-body">
                                <form method="POST" action="{{ route('teacher.update', $teacher->id) }}" enctype="multipart/form-data" class="forms-sample">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Name" value="{{ $teacher->name }}" required>
                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Position</label>
                                        <input type="text" name="position" class="form-control @error('position') is-invalid @enderror" placeholder="Position" value="{{ $teacher->position }}" required>
                                        @error('position')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Motto</label>
                                        <input type="text" name="motto" class="form-control @error('motto') is-invalid @enderror" placeholder="Motto" value="{{ $teacher->motto }}" required>
                                        @error('motto')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Avatar <i style="font-size: 10px">(maks 600 x 700 250kb)</i></label>
                                        <br>
                                        <img src="{{ $teacher->avatar }}" class="img-fluid mb-1" alt="">
                                        <input type="file" name="avatar" class="form-control @error('avatar') is-invalid @enderror">
                                        @error('avatar')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="row">
                                        @php $media = json_decode($teacher->media) @endphp
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Facebook Link</label>
                                                <input type="text" name="facebook" class="form-control @error('facebook') is-invalid @enderror" placeholder="Facebook" value="{{ $media->facebook }}">
                                                @error('facebook')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Twitter Link</label>
                                                <input type="text" name="twitter" class="form-control @error('twitter') is-invalid @enderror" placeholder="Twitter" value="{{ $media->twitter }}">
                                                @error('twitter')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>LinkedIn Link</label>
                                                <input type="text" name="linkedin" class="form-control @error('linkedin') is-invalid @enderror" placeholder="LinkedIn" value="{{ $media->linkedin }}">
                                                @error('linkedin')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Instagram Link</label>
                                                <input type="text" name="instagram" class="form-control @error('instagram') is-invalid @enderror" placeholder="Instagram" value="{{ $media->instagram }}">
                                                @error('instagram')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-rounded mr-2">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/teacher/index.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Teacher</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('teacher.index') }}">Teacher</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Index
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height">
                @foreach ($teachers as $teacher)
                <div class="col-lg-3 col-md-3">
                    <div class="card">
                        <div class="card-body block-teacher__card-body">
                            <h4 class="card-title block-teacher__card-body-title">{{ $teacher->name }}</h4>
                        </div>
                        <img class="block-teacher__card-image" src="{{ $teacher->avatar }}" alt="Card image">
                        <div class="card-body text-center block-teacher__card-body-quote">
                            {{ Str::words($teacher->motto, 15) }}
                        </div>
                        <div class="card-footer block-teacher__card-footer border-top-blue-grey border-top-lighten-5 text-muted">
                            <div class="block-teacher__card-footer-grid">
                                <div class="block-teacher__card-footer-grid-item">
                                    <button class="btn btn-info full-width" title="Edit" onclick="window.location='{{ route('teacher.edit', $teacher->id) }}'">
                                        <i class="ft-edit"></i> Edit
                                    </button>
                                </div>
                                <div class="block-teacher__card-footer-grid-item">
                                    <form action="{{ route('teacher.destroy', $teacher->id) }}" method="POST" onsubmit="return confirm('Are you sure?')">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger full-width" title="Delete">
                                            <i class="ft-trash"></i> Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            <div class="row block-nav justify-content-center">
                <div class="col-lg-12 col-7 block-nav__box">
                   {{ $teachers->links() }}
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-primary btn-sticky no-padding" title="Add New" onclick="window.location='{{ route('teacher.create') }}'">
        <i class="ft-plus la-3x"></i>
    </button>
</div>
@endsection