routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/dashboard', 'Admin\DashboardController@index')
    ->name('dashboard')
    ->middleware(['auth']);

Route::resource('admin', 'Admin\AdminController')
    ->middleware('auth');

Route::resource('banner', 'Admin\BannerController')
    ->middleware('auth');

Route::resource('about', 'Admin\AboutController')
    ->middleware('auth')
    ->only(['edit', 'update']);

Route::resource('program', 'Admin\ProgramController')
    ->middleware('auth');

Route::resource('teacher', 'Admin\TeacherController')
    ->middleware('auth');

Route::resource('event', 'Admin\EventController')
    ->middleware('auth');

Route::resource('news', 'Admin\NewsController')
    ->middleware('auth');

Route::resource('gallery', 'Admin\GalleryController')
    ->middleware('auth');

Route::get('gallery-stage/{stage}', 'Admin\GalleryController@indexStage')
    ->name('gallery.stage')
    ->middleware('auth');

Route::prefix('pdb')
    ->name('pdb.')
    ->middleware(['auth'])
    ->group(function () {

        Route::get('manage/list/{status}/{stage}', 'Admin\RegisterController@index')
            ->name('index');

        Route::get('manage/detail/{id}', 'Admin\RegisterController@detail')
            ->name('detail');

        Route::get('manage/print/{id}', 'Admin\RegisterController@print')
            ->name('print');

        Route::put('manage/process/{id}', 'Admin\RegisterController@process')
            ->name('process');
    });




Route::get('/', 'Frontend\HomeController@index')
    ->name('front.home');

Route::get('profil-kami', 'Frontend\AboutController@index')
    ->name('front.about');

Route::get('program-unggulan', 'Frontend\ProgramController@index')
    ->name('front.program');

Route::get('program-unggulan/{slug}', 'Frontend\ProgramController@detail')
    ->name('front.program.detail');

Route::get('acara', 'Frontend\EventController@index')
    ->name('front.event');

Route::get('acara/{slug}', 'Frontend\EventController@detail')
    ->name('front.event.detail');

Route::get('berita', 'Frontend\NewsController@index')
    ->name('front.news');

Route::get('berita/{slug}', 'Frontend\NewsController@detail')
    ->name('front.news.detail');

Route::get('galeri', 'Frontend\GalleryController@index')
    ->name('front.gallery');

Route::get('galeri/{stage}', 'Frontend\GalleryController@indexStage')
    ->name('front.gallery.stage');

Route::get('kontak', 'Frontend\ContactController@index')
    ->name('front.contact');

Route::prefix('pdb')
    ->name('front.pdb.')
    ->group(function () {

        Route::get('step-1', 'Frontend\RegisterController@stepOne')
            ->name('step-1');

        Route::get('step-2', 'Frontend\RegisterController@stepTwo')
            ->name('step-2');

        Route::get('step-3', 'Frontend\RegisterController@stepThree')
            ->name('step-3');

        Route::get('step-4', 'Frontend\RegisterController@stepFour')
            ->name('step-4');

        Route::get('step-5', 'Frontend\RegisterController@stepFive')
            ->name('step-5');

        Route::get('step-6', 'Frontend\RegisterController@stepSix')
            ->name('step-6');

        Route::get('complete', 'Frontend\RegisterController@complete')
            ->name('complete');

        Route::post('store/{step}', 'Frontend\RegisterController@store')
            ->name('store');
    });

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    //
}

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Gallery;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreGallery;
use App\Http\Requests\UpdateGallery;
use App\Services\CloudinaryService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.gallery.index', [
            'galleries' => Gallery::orderBy('id', 'DESC')->paginate(8)
        ]);
    }

    public function indexStage($stage)
    {
        if (! in_array($stage, ['TK', 'SD', 'SMP'])) {
            abort(404);
        }

        session([
            'gallery' => $stage
        ]);

        return view('admin.gallery.index', [
            'galleries' => Gallery::where('stage', $stage)->orderBy('id', 'DESC')->paginate(8)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreGallery $request)
    {
        $request->validated();

        $gallery = new Gallery;
        $gallery->stage = session('gallery');
        $gallery->title = $request->input('title');
        $gallery->image = CloudinaryService::upload($request->file('image'));
        $gallery->slug = Str::slug($gallery->title);

        if($gallery->save()) {
            return redirect()->route('gallery.stage', session('gallery'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function show(Gallery $gallery)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.gallery.edit', [
            'gallery' => Gallery::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateGallery $request, $id)
    {
        $request->validated();

        $gallery = Gallery::findOrFail($id);
        $gallery->title = $request->input('title');
        $gallery->slug = Str::slug($gallery->title);

        if ($request->file('image')) {
            CloudinaryService::remove($gallery->image);
            $gallery->image = CloudinaryService::upload($request->file('image'));
        }

        if($gallery->save()) {
            return redirect()->route('gallery.stage', session('gallery'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $gallery = Gallery::findOrFail($id);
        if($gallery->delete()) {
            CloudinaryService::remove($gallery->image);
            return redirect()->route('gallery.stage', session('gallery'));
        }
    }
}

app/Http/Controllers/Frontend/GalleryController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\About;
use App\Event;
use App\Gallery;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    public function index()
    {
        return view('frontend.gallery.index', [
            'events' => Event::orderBy('id', 'DESC')->limit(3)->get(),
            'galleries' => Gallery::orderBy('id', 'DESC')->paginate(9)
        ]);
    }

    public function indexStage($stage)
    {
        if (! in_array($stage, ['TK', 'SD', 'SMP'])) {
            abort(404);
        }

        return view('frontend.gallery.index', [
            'events' => Event::orderBy('id', 'DESC')->limit(3)->get(),
            'galleries' => Gallery::where('stage', $stage)->orderBy('id', 'DESC')->paginate(9),
            'stage' => $stage
        ]);
    }
}

resources/views/admin/gallery/create.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Gallery</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('gallery.index') }}">Gallery</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Create
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height justify-content-center">
                <div class="col-xl-10 col-lg-10 col-md-10 col-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-body">
                                <form method="POST" action="{{ route('gallery.store') }}" enctype="multipart/form-data" class="forms-sample">
                                    @csrf
                                    <div class="form-group">
                                        <label>Image <i style="font-size: 10px">(maks 850 x 850 350kb)</i></label>
                                        <input type="file" name="image" class="form-control @error('image') is-invalid @enderror" required>
                                        @error('image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Caption</label>
                                        <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" placeholder="Caption" value="{{ old('title') }}" required>
                                        @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-rounded mr-2">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/gallery/edit.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Gallery</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('gallery.index') }}">Gallery</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Edit
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height justify-content-center">
                <div class="col-xl-10 col-lg-10 col-md-10 col-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-body">
                                <form method="POST" action="{{ route('gallery.update', $gallery->id) }}" enctype="multipart/form-data" class="forms-sample">
                                    @csrf
                                    @method ('PUT')
                                    <div class="form-group">
                                        <label>Image <i style="font-size: 10px">(maks 850 x 850 350kb)</i></label>
                                        <br>
                                        <img src="{{ $gallery->image }}" class="img-fluid mb-1" alt="">
                                        <input type="file" name="image" class="form-control @error('image') is-invalid @enderror">
                                        @error('image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Caption</label>
                                        <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" placeholder="Caption" value="{{ $gallery->title }}" required>
                                        @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-rounded mr-2">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/gallery/index.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Gallery</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('gallery.index') }}">Gallery</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Index
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height">
                @foreach ($galleries as $gallery)
                <div class="col-lg-3 col-md-3">
                    <div class="card">
                        <img class="block-gallery__card-image" src="{{ $gallery->image }}" alt="Card image">
                        <div class="card-footer block-gallery__card-footer border-top-blue-grey border-top-lighten-5 text-muted">
                            <div class="block-gallery__card-footer-grid">
                                <div class="block-gallery__card-footer-grid-item">
                                    <button class="btn btn-info full-width" title="Edit" onclick="window.location='{{ route('gallery.edit', $gallery->id) }}'">
                                        <i class="ft-edit"></i> Edit
                                    </button>
                                </div>
                                <div class="block-gallery__card-footer-grid-item">
                                    <form action="{{ route('gallery.destroy', $gallery->id) }}" method="POST" onsubmit="return confirm('Are you sure?')">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger full-width" title="Delete">
                                            <i class="ft-trash"></i> Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            <div class="row block-nav justify-content-center">
                <div class="col-lg-12 col-7 block-nav__box">
                   {{ $galleries->links() }}
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-primary btn-sticky no-padding" title="Add New" onclick="window.location='{{ route('gallery.create') }}'">
        <i class="ft-plus la-3x"></i>
    </button>
</div>
@endsection