routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/dashboard', 'Admin\DashboardController@index')
    ->name('dashboard')
    ->middleware(['auth']);

Route::resource('admin', 'Admin\AdminController')
    ->middleware('auth');

Route::resource('banner', 'Admin\BannerController')
    ->middleware('auth');

Route::resource('about', 'Admin\AboutController')
    ->middleware('auth')
    ->only(['edit', 'update']);

Route::resource('program', 'Admin\ProgramController')
    ->middleware('auth');

Route::resource('teacher', 'Admin\TeacherController')
    ->middleware('auth');

Route::resource('event', 'Admin\EventController')
    ->middleware('auth');

Route::resource('news', 'Admin\NewsController')
    ->middleware('auth');

Route::resource('gallery', 'Admin\GalleryController')
    ->middleware('auth');

Route::get('gallery-stage/{stage}', 'Admin\GalleryController@indexStage')
    ->name('gallery.stage')
    ->middleware('auth');

Route::prefix('pdb')
    ->name('pdb.')
    ->middleware(['auth'])
    ->group(function () {

        Route::get('manage/list/{status}/{stage}', 'Admin\RegisterController@index')
            ->name('index');

        Route::get('manage/detail/{id}', 'Admin\RegisterController@detail')
            ->name('detail');

        Route::get('manage/print/{id}', 'Admin\RegisterController@print')
            ->name('print');

        Route::put('manage/process/{id}', 'Admin\RegisterController@process')
            ->name('process');
    });




Route::get('/', 'Frontend\HomeController@index')
    ->name('front.home');

Route::get('profil-kami', 'Frontend\AboutController@index')
    ->name('front.about');

Route::get('program-unggulan', 'Frontend\ProgramController@index')
    ->name('front.program');

Route::get('program-unggulan/{slug}', 'Frontend\ProgramController@detail')
    ->name('front.program.detail');

Route::get('acara', 'Frontend\EventController@index')
    ->name('front.event');

Route::get('acara/{slug}', 'Frontend\EventController@detail')
    ->name('front.event.detail');

Route::get('berita', 'Frontend\NewsController@index')
    ->name('front.news');

Route::get('berita/{slug}', 'Frontend\NewsController@detail')
    ->name('front.news.detail');

Route::get('galeri', 'Frontend\GalleryController@index')
    ->name('front.gallery');

Route::get('galeri/{stage}', 'Frontend\GalleryController@indexStage')
    ->name('front.gallery.stage');

Route::get('kontak', 'Frontend\ContactController@index')
    ->name('front.contact');

Route::prefix('pdb')
    ->name('front.pdb.')
    ->group(function () {

        Route::get('step-1', 'Frontend\RegisterController@stepOne')
            ->name('step-1');

        Route::get('step-2', 'Frontend\RegisterController@stepTwo')
            ->name('step-2');

        Route::get('step-3', 'Frontend\RegisterController@stepThree')
            ->name('step-3');

        Route::get('step-4', 'Frontend\RegisterController@stepFour')
            ->name('step-4');

        Route::get('step-5', 'Frontend\RegisterController@stepFive')
            ->name('step-5');

        Route::get('step-6', 'Frontend\RegisterController@stepSix')
            ->name('step-6');

        Route::get('complete', 'Frontend\RegisterController@complete')
            ->name('complete');

        Route::post('store/{step}', 'Frontend\RegisterController@store')
            ->name('store');
    });

app/Pdb.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pdb extends Model
{
    protected $table = 'pdb';
}

resources/views/admin/pdb/index.blade.php
@extends('admin.layouts.extend')

@section('content')
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">PPDB</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('news.index') }}">PPDB</a>
                            </li>
                            <li class="breadcrumb-item active">
                                @if (Route::current()->parameter('status') == 1)
                                Baru
                                @else
                                Proses
                                @endif
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row match-height justify-content-center">
                <div class="col-xl-10 col-lg-10 col-md-10 col-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-body">
                                <div class="form-group">
                                    <select class="form-control" name="stage">
                                        <option value="all" @if($stage == 'all') selected @endif>Semua</option>
                                        <option value="TK" @if($stage == 'TK') selected @endif>TK</option>
                                        <option value="SD" @if($stage == 'SD') selected @endif>SD</option>
                                        <option value="SMP" @if($stage == 'SMP') selected @endif>SMP</option>
                                    </select>
                                </div>
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>No Pendaftaran</th>
                                            <th>Jenjang</th>
                                            <th>Nama</th>
                                            <th>No HP</th>
                                            <th>Tanggal Daftar</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($pdbs as $index => $pdb)
                                        @php $student = json_decode($pdb->student) @endphp
                                        <tr>
                                            <th scope="row">{{ $index + 1 }}</th>
                                            <td>{{ $pdb->visitor }}</td>
                                            <td>@if(! empty($student->stage)){{ $student->stage }}@else-@endif</td>
                                            <td>{{ $student->name }}</td>
                                            <td>{{ $student->phone }}</td>
                                            <td>{{ $pdb->created_at }}</td>
                                            <td>
                                                @if ($pdb->status == 1)
                                                <div class="block-news__card-footer-grid">
                                                    <div class="block-news__card-footer-grid-item">
                                                        <button class="btn btn-success full-width" title="Detail" onclick="window.location='{{ route('pdb.detail', $pdb->id) }}'">
                                                            <i class="ft-sun"></i> LIHAT
                                                        </button>
                                                    </div>
                                                    <div class="block-news__card-footer-grid-item">
                                                        <form action="{{ route('pdb.process', $pdb->id) }}" method="POST" onsubmit="return confirm('Are you sure?')">
                                                            @csrf
                                                            @method('PUT')
                                                            <button class="btn btn-info full-width" title="Process">
                                                                <i class="ft-check-square"></i> PROSES
                                                            </button>
                                                        </form>
                                                    </div>
                                                </div>
                                                @else
                                                <div class="block-news__card-footer-grid-item">
                                                    <button class="btn btn-success full-width" title="Detail" onclick="window.location='{{ route('pdb.detail', $pdb->id) }}'">
                                                        <i class="ft-sun"></i> LIHAT
                                                    </button>
                                                </div>
                                                @endif
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row block-nav justify-content-center">
                <div class="col-lg-12 col-7 block-nav__box">
                    {{ $pdbs->links() }}
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-primary btn-sticky no-padding" title="Add New" onclick="window.location='{{ route('news.create') }}'">
        <i class="ft-plus la-3x"></i>
    </button>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function() {
        $('[name=stage]').change(function() {
            window.location = $(this).val();
        })
    })
</script>
@endsection

resources/views/admin/pdb/print.blade.php
<style>
    th {
        width: 50%;
    }

    td {
        width: 50%;
    }

    .pdb-separator-tr {
        background: #eee;
        border: none;
        height: 12px
    }

    div {
        justify-content: center;
    }

    div table {
        text-align: left
    }
</style>
<div>
    <table class="table table-borderless" id="table">
        <tr>
            <th>Nama Lengkap</th>
            <td>{{ $student->name }}</td>
        </tr>
        <tr>
            <th>Jenis Kelamin</th>
            <td>{{ $student->gender }}</td>
        </tr>
        <tr>
            <th>Jenjang Pendaftaran</th>
            <td>@if(! empty($student->stage)){{ $student->stage }}@else-@endif</td>
        </tr>
        <tr>
            <th>Nomor Induk Siswa Nasional</th>
            <td>{{ $student->nisn }}</td>
        </tr>
        <tr>
            <th>Nomor Induk Kependudukan</th>
            <td>{{ $student->nik }}</td>
        </tr>
        <tr>
            <th>Tempat dan Tanggal Lahir</th>
            <td>{{ $student->birth_place }}, {{ $student->birth_date }}-{{ $student->birth_month }}-{{ $student->birth_year }}</td>
        </tr>
        <tr>
            <th>Agama</th>
            <td>{{ $student->religion }}</td>
        </tr>
        <tr>
            <th>Berkebutuhan Khusus</th>
            <td>{{ $student->disability }}</td>
        </tr>
        <tr>
            <th>Alamat Tempat Tinggal</th>
            <td>
                {{ $student->address }} <br>
                <strong>Dusun</strong> {{ $student->village}} | <strong>RT</strong> {{ $student->rt}} | <strong>RW</strong> {{ $student->rw}} <br>
                <strong>Kelurahan / Desa</strong> {{ $student->village_office }} | <strong>Kode Pos</strong> {{ $student->postal_code }} <br>
                <strong>Kecamatan</strong> {{ $student->sub_district }} <br>
                <strong>Kabupaten / Kota</strong> {{ $student->city }} <br>
                <strong>Provinsi</strong> {{ $student->province }}
            </td>
        </tr>
        <tr>
            <th>Kendaraan Sekolah</th>
            <td>{{ $student->vehicle }}</td>
        </tr>
        <tr>
            <th>Jenis Tinggal</th>
            <td>{{ $student->live }}</td>
        </tr>
        <tr>
            <th>Telepon Rumah</th>
            <td>@if (! empty($student->house_phone)){{ $student->house_phone}}@else - @endif</td>
        </tr>
        <tr>
            <th>No. HP</th>
            <td>{{ $student->phone }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>@if (! empty($student->email)){{ $student->email}}@else - @endif</td>
        </tr>
        <tr>
            <th>Penerima KPS</th>
            <td>
                {{ $student->kps }} <br>
                <strong>No KPS</strong> @if (! empty($student->kps_number)){{ $student->kps_number}}@else - @endif
            </td>
        </tr>
        <tr>
            <th>Kewarganegaraan</th>
            <td>{{ $student->nationality }}</td>
        </tr>
        <tr>
            <th>Usulan Layak PP</th>
            <td>{{ $student->pp }}</td>
        </tr>
        <tr>
            <th>Bank</th>
            <td>@if (! empty($student->bank)){{ $student->bank}}@else - @endif</td>
        </tr>
        <tr>
            <th>No Rekening Bank</th>
            <td>@if (! empty($student->bank_account)){{ $student->bank_account}}@else - @endif</td>
        </tr>
        <tr class="pdb-separator-tr">
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th>Nama Ayah</th>
            <td>{{ $student->father_name }}</td>
        </tr>
        <tr>
            <th>Tahun Lahir</th>
            <td>{{ $student->father_birth_year }}</td>
        </tr>
        <tr>
            <th>Berkebutuhan Khusus</th>
            <td>{{ $student->father_disability }}</td>
        </tr>
        <tr>
            <th>Pekerjaan</th>
            <td>{{ $student->father_job }}</td>
        </tr>
        <tr>
            <th>Pendidikan</th>
            <td>{{ $student->father_education }}</td>
        </tr>
        <tr>
            <th>Penghasilan Bulanan</th>
            <td>{{ $student->father_salary }}</td>
        </tr>
        <tr class="pdb-separator-tr">
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th>Nama Ibu</th>
            <td>{{ $student->mother_name }}</td>
        </tr>
        <tr>
            <th>Tahun Lahir</th>
            <td>{{ $student->mother_birth_year }}</td>
        </tr>
        <tr>
            <th>Berkebutuhan Khusus</th>
            <td>{{ $student->mother_disability }}</td>
        </tr>
        <tr>
            <th>Pekerjaan</th>
            <td>{{ $student->mother_job }}</td>
        </tr>
        <tr>
            <th>Pendidikan</th>
            <td>{{ $student->mother_education }}</td>
        </tr>
        <tr>
            <th>Penghasilan Bulanan</th>
            <td>{{ $student->mother_salary }}</td>
        </tr>
        <tr class="pdb-separator-tr">
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th>Nama Wali</th>
            <td>@if (! empty($student->guardian_name)){{ $student->guardian_name}}@else - @endif</td>
        </tr>
        <tr>
            <th>Tahun Lahir</th>
            <td>@if (! empty($student->guardian_birth_year)){{ $student->guardian_birth_year}}@else - @endif</td>
        </tr>
        <tr>
            <th>Berkebutuhan Khusus</th>
            <td>@if (! empty($student->guardian_disability)){{ $student->guardian_disability}}@else - @endif</td>
        </tr>
        <tr>
            <th>Pekerjaan</th>
            <td>@if (! empty($student->guardian_job)){{ $student->guardian_job}}@else - @endif</td>
        </tr>
        <tr>
            <th>Pendidikan</th>
            <td>@if (! empty($student->guardian_education)){{ $student->guardian_education}}@else - @endif</td>
        </tr>
        <tr>
            <th>Penghasilan Bulanan</th>
            <td>@if (! empty($student->guardian_salary)){{ $student->guardian_salary}}@else - @endif</td>
        </tr>
        <tr class="pdb-separator-tr">
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th>Tinggi Badan</th>
            <td>{{ $student->height }} cm</td>
        </tr>
        <tr>
            <th>Berat Badan</th>
            <td>{{ $student->weight }} cm</td>
        </tr>
        <tr>
            <th>Jarak Tempat Tinggal ke Sekolah</th>
            <td>{{ $student->distance }} km</td>
        </tr>
        <tr>
            <th>Waktu Tempuh</th>
            <td>{{ $student->distance_time }} menit</td>
        </tr>
        <tr>
            <th>Jumlah Saudara Kandung</th>
            <td>{{ $student->brother }}</td>
        </tr>
        <tr class="pdb-separator-tr">
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th>Catatan Prestasi</th>
            <td>
                @if (! empty($achievements))
                <ol>
                    @foreach ($student->achievements as $achievement)
                    <li class="mb-2">
                        <strong>Jenis Prestasi</strong> : @if (! empty($achievement->kind)){{ $achievement->kind}}@else - @endif <br>
                        <strong>Tingkat</strong> : @if (! empty($achievement->level)){{ $achievement->level}}@else - @endif <br>
                        <strong>Nama Prestasi</strong> : @if (! empty($achievement->name)){{ $achievement->name}}@else - @endif <br>
                        <strong>Tahun</strong> : @if (! empty($achievement->year)){{ $achievement->year}}@else - @endif <br>
                        <strong>Penyelenggara</strong> : @if (! empty($achievement->organizer)){{ $achievement->organizer}}@else - @endif <br>
                    </li>
                    @endforeach
                </ol>
                @else
                -
                @endif
            </td>
        </tr>
        <tr class="pdb-separator-tr">
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th>Beasiswa</th>
            <td>
                @if (! empty($scholarships))
                <ol>
                    @foreach ($student->scholarships as $scholarship)
                    <li class="mb-2">
                        <strong>Jenis</strong> : @if (! empty($scholarship->kind)){{ $scholarship->kind}}@else - @endif <br>
                        <strong>Penyelenggara / Sumber</strong> : @if (! empty($scholarship->organizer)){{ $scholarship->organizer}}@else - @endif <br>
                        <strong>Tahun Mulai</strong> : @if (! empty($scholarship->year_start)){{ $scholarship->year_start}}@else - @endif <br>
                        <strong>Tahun Selesai</strong> : @if (! empty($scholarship->year_finish)){{ $scholarship->year_finish}}@else - @endif <br>
                    </li>
                    @endforeach
                </ol>
                @else
                -
                @endif
            </td>
        </tr>
        <tr class="pdb-separator-tr">
            <th></th>
            <td></td>
        </tr>
        <tr class="pdb-separator-tr">
            <th></th>
            <td></td>
        </tr>
        <tr class="pdb-separator-tr">
            <th></th>
            <td></td>
        </tr>
        <tr>
            <th>Tanggal Pendaftaran</th>
            <td>{{ $model->created_at }}</td>
        </tr>
    </table>
</div>

<script>
    window.print();
    setTimeout(function() {
        var table = document.getElementById('table');
        table.style.display = 'none'
    }, 2000)
</script>